### PR TITLE
fix some scripts for ros noetic

### PR DESCRIPTION
**Pull request by dieu-detruit**
Change some files because the current codes are not compatible to ROS Noetic.

### CODE REVIEW

**Comment by zlj-zz** [comment]
Have you tested it on kinetic? Is it compatible?

**Comment by dieu-detruit** [comment]
This is not compatible to kinetic, so please make a “noetic” branch and pull this request.  🙇‍♂️

**Comment by zlj-zz** [comment]
OK.Thank you.Sent from my iPhone------------------ Original ------------------From: Takafumi Watanabe  ***@***.***>Date: Fri, Apr 16, 2021 8:48 PMTo: elephantrobotics/myCobotROS ***@***.***>Cc: Zachary ***@***.***>, Comment ***@***.***>Subject: Re: [elephantrobotics/myCobotROS] fix some scripts for ros noetic(#14)
This is not compatible to kinetic, so please make a “noetic” branch and pull this request.  🙇‍♂️

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/elephantrobotics/myCobotROS/pull/14#issuecomment-821149786",
"url": "https://github.com/elephantrobotics/myCobotROS/pull/14#issuecomment-821149786",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by zlj-zz** [comment]
Some users reported that they could not use this branch on noetic. 
Can you give a new readme and some screenshots? At present, I have no environment to test it, thank you

**Comment by dieu-detruit** [comment]
Sorry, I changed the package name from myCobotROS to mycobot_ros because the former one does not follow the naming rule of ROS, but I didn't edited the README.
I will make a new pull request with some fixes. Please wait for some time. Thank you.

**Comment by apockill** [comment]
@dieu-detruit if you're interested, it could be possible to support both `kinetic` and `noetic` builds using docker. I just added a docker-compose workflow (documented in the readme). We could have a `noetic-ros` run configuration, which would build from a separate `Dockerfile.noetic`. The default `Dockerfile` currently builds a `kinetic` environment.

**Comment by dieu-detruit** [comment]
@apockill 
Thank you. I have already made a new PR ([#16](https://github.com/elephantrobotics/myCobotROS/pull/16)), which merged your docker workflows (only for noetic).

Now I have a difficulty in trying to supporting both kinetic and noetic on a same branch:
- Some dependencies have different name between two distro. (package.xml varies)

Do you have any idea to diverge package names on package.xml? (cmake has if statement though)

**Comment by apockill** [comment]
:sweat_smile: unfortunately I do not! I'm completely new to the ROS ecosystem.

**Comment by fedorenchik** [comment]
@all-contributors please add @dieu-detruit for code

**Pull request closed without merging**
