### PR TITLE
Support both nvidia/without nvidia

### PR DESCRIPTION
**Pull request by Tiryoh**
This is a fix of #15

Tested on 
* Ubuntu 18.04 with GPU
    * CPU: Intel Core i5-9600K
    * GPU: RTX2070 super
* Ubuntu 18.04 with Intel Integrated GPU
    * CPU: Intel Core i7-8650U

### CODE REVIEW

**Comment by zlj-zz** [comment]
For your testing, it's ok.

**Comment by Tiryoh** [comment]
@zlj-zz Is there anything I need to do to get this PR to be merged? Are the listed 2 environments not enough?

**Comment by zlj-zz** [comment]
I think it's enough. But we need to test ourselves to ensure it.

Now we have other work to do. I'll merge it when we test it.😊

**Comment by Tiryoh** [comment]
OK! Thanks for sharing. I'm looking forward to it.

**Comment by fedorenchik** [comment]
@all-contributors please add @Tiryoh for doc, code.

**Pull request merged**
