### PR TITLE
Explicitly specify pip3 to avoid pulling python2 dependencies

### PR DESCRIPTION
**Pull request by apockill**
This resolves https://github.com/elephantrobotics/mycobot_ros/issues/37

### CODE REVIEW

**Comment by fedorenchik** [comment]
Thank you, but is it possible / needed to keep support Python 2.7 ?

**Comment by fedorenchik** [comment]
Anyway, I've merged since it fixes #37.

**Comment by apockill** [comment]
It's probably best to drop 2.7 support, given that it's no longer maintained. Is there any specific reason to use 2.7?

**Comment by fedorenchik** [comment]
@apockill I guess can drop python 2.7 unless there will be user requests to keep it.

kinetic and melodic use python 2.7 and melodic is still the most popular ROS distro https://metrics.ros.org/packages_rosdistro.html and kinetic has most packages https://metrics.ros.org/rosdistro_numberofrepos.html

**Comment by apockill** [comment]
Got it, thank you for the explanation. I'm not an expert with ROS yet :grin: 

Here's hoping the ecosystem moves to python 3+!

**Pull request merged**
