### PR TITLE
Do you add ros-${ROS_DISTRO}-moveit, and modify docker-compose.yml to use ROS1 melodic?

### PR DESCRIPTION
**Pull request by graziegrazie**
About dockerfile, current mycobot_ros depends on moveit heavily. When I performed "docker-compose build ros",  I faced "Could not find moveit_msgs". Then, I checked package.xml and found out that mycobot_ros package depends on several moveit related packages.

About docker-compose, there are two reasons.
1) ROS1 kinetic has been already EOL.
2) "docker-compose build ros" failed when I added ros-kinetic-moveit
When I performed "docker-compose build ros" with Dockerfile incl. moveit and ROS_DISTRO = kinetic. I faced following error while installing packages.

```
.... 
Preparing to unpack .../ros-kinetic-serial_1.2.1-0xenial-20191214-001149+0000_amd64.deb ...
Unpacking ros-kinetic-serial (1.2.1-0xenial-20191214-001149+0000) ...
Processing triggers for libc-bin (2.23-0ubuntu11.2) ...
dpkg: error: error executing hook 'if { test "$DPKG_HOOK_ACTION" = add-architecture || test "$DPKG_HOOK_ACTION" = remove-architecture; } && test -x /usr/share/pkg-config-dpkghook; then /usr/share/pkg-config-dpkghook update; fi', exit code 139
E: Sub-process /usr/bin/dpkg returned an error code (2)
E: Problem executing scripts DPkg::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'
E: Sub-process returned an error code
ERROR: Service 'ros' failed to build: The command '/bin/bash -c apt-get update &&     apt-get install -y         python-rosinstall         python-rosinstall-generator         python-wstool         build-essential         python-pip         ros-kinetic-moveit         ros-${ROS_DISTRO}-serial         ros-${ROS_DISTRO}-joint-state-publisher-gui &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

I also tried apt-get install on a container from osrf/ros:kinetic-desktop-full. In this case, I did not face the error above, and completed them. I'm not sure why this gap occurred. 

Then, since kinetic is EOL, I tried with osrf/ros:melodic-desktop-full and ROS_DISTRO = melodic. In this case, I completed docker-compuse build.

### CODE REVIEW

**Comment by zlj-zz** [comment]
`I also tried apt-get install on a container from osrf/ros:kinetic-desktop-full. In this case, I did not face the error above, and completed them. I'm not sure why this gap occurred.`  What does this sentence mean?

**Comment by zlj-zz** [comment]
And after you changed the version to `melodic`, is everything ok?

**Comment by zlj-zz** [comment]
And after you changed the version to `melodic`, is everything ok?

**Comment by graziegrazie** [comment]
> `I also tried apt-get install on a container from osrf/ros:kinetic-desktop-full. In this case, I did not face the error above, and completed them. I'm not sure why this gap occurred.` What does this sentence mean?
I mean I did following sequence.
1. create a container from osrf/ros:kinetic-desktop-full without apt-get install
2. came into the container created in 1.
3. did apt-get install packages in Dockerfile. Successfully installed packages.

I tested demo.launch and demo_gazebo.launch. About demo.launch, I can plan and execute the plan. About demo_gazebo.launch, I cannot spawn model. I also tried on local machine with Ubuntu 20.04 and ROS Noetic, but cannot spawn model on gazebo.

And, I don't have mycobot yet, so I cannot test launch with a real robot. I'm so sorry.

**Comment by Tiryoh** [comment]
I think using `rosdep` will solve the problem about adding missing package.
rosdep: http://wiki.ros.org/rosdep
usage: https://github.com/Tiryoh/mycobot_ros#installation
To use rosdep, it is required to maintain `package.xml` correctly. I made a PR #24  for this.

@graziegrazie I made a PR to `graziegrazie:docker` for using rosdep, so please check it out.
https://github.com/graziegrazie/mycobot_ros/pull/1
This PR contains several commit, but the only changes for using rosdep is this commit: https://github.com/graziegrazie/mycobot_ros/commit/a036806572003d8e78a64fe386416a60ae753510
The other commits are the contents of #24.

After merging both #24 and https://github.com/graziegrazie/mycobot_ros/pull/1, It worked on my PC with myCobot.
The sources for both merged cases can be found here.
https://github.com/Tiryoh/elephantrobotics_mycobot_ros/tree/feature/docker-compose-launch

**Comment by graziegrazie** [comment]
@Tiryoh Thank you for your comment and suggestion!
I checked your PR. As far as I tried "roslaunch mycobot_ros demo.launch", your commit works well.
Since I don't have a real myCobot yet, I tested your commit without it.

**Comment by Tiryoh** [comment]
@graziegrazie Thanks for checking it out!

> As far as I tried "roslaunch mycobot_ros demo.launch", your commit works well.

Great! I guess you can also test the default launch (`mycobot_slider.launch`) which does not requires the actual myCobot for now.
https://github.com/graziegrazie/mycobot_ros/blob/92637577051096df3046154b35f2cb05576b012c/launch/mycobot_slider.launch#L18-L21

**Comment by zlj-zz** [comment]
Thank you for your contribution. I think it's OK, so I merged it.

**Comment by fedorenchik** [comment]
@all-contributors please add @graziegrazie for code

**Pull request merged**
